# Generated by Django 4.1.2 on 2023-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
