# Generated by Django 4.1.2 on 2023-10-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_productor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='productor',
            field=models.CharField(max_length=30),
        ),
    ]
