# Generated by Django 4.1.2 on 2023-10-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_productor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='productor',
        ),
    ]
