# Generated by Django 4.1.2 on 2023-11-03 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='xvalue',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='item',
            name='yvalue',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
