# Generated by Django 4.1.2 on 2023-11-08 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='product_name',
            field=models.CharField(default=None, max_length=30, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='メッセージ'),
        ),
    ]
