# Generated by Django 4.1.2 on 2023-11-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contactmodel_product_name_alter_contactmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='product_name',
            field=models.CharField(max_length=30, null=True, verbose_name='商品名'),
        ),
    ]
