# Generated by Django 4.1.2 on 2023-10-12 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message="郵便番号は次のように入力してください。'1234567'、7桁まで入力可能です。", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="電話番号は次のように入力してください。'09012345678'、１５桁まで入力可能です。", regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
